on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export

      - name: Create artifacts folder
        run: mkdir -p artifacts

      - name: Build Sofle Left
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=sofle_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Sofle Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Copy left UF2
        run: cp build/zephyr/zmk.uf2 artifacts/sofle_left_nice_nano_v2.uf2

      - name: Build Sofle Right
        run: west build --pristine -s zmk/app -b nice_nano_v2 -- -DSHIELD=sofle_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Sofle Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Copy right UF2
        run: cp build/zephyr/zmk.uf2 artifacts/sofle_right_nice_nano_v2.uf2

      - name: Upload both UF2 files
        uses: actions/upload-artifact@v4
        with:
          name: firmwares
          path: |
            artifacts/sofle_left_nice_nano_v2.uf2
            artifacts/sofle_right_nice_nano_v2.uf2
